# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef79adfb91ef472619a252b846a9493833f89377f41bb98c30b5026557e5c1c37b2d3f4a5a1f244e2f036427b390c45501c85250382531cc2f3cc29e8fe64366

test:
  secret_key_base: 2632fcd289d195a4195d36bcd41ba3f2149e47393e439cac1ebb69336b043092a90f17943ac8a02a9479aa8f737e151d1e2e09553f93302abbe40c1789e2a306

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
